{% set name = "pyometiff" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyometiff-{{ version }}.tar.gz
  sha256: 4d2f354c971caad5b46f2ce603fccf6265d5c88f15f2d8df6e87c2118ca53869
  patches:
    - require.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - lxml >=5.3.2,<6.0.0
    - tifffile >2020.10.1
    - numpy >=1.26.4
    - imagecodecs >=2024.12.30

test:
  imports:
    - pyometiff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/filippocastelli/pyometiff
  summary: Read and Write OME-TIFFs in Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
