{% set name = "pyometiff" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyometiff-{{ version }}.tar.gz
  sha256: 517879948e62670009f171183065d4bc07269a24d306436bfe18007dd2e2429b
  patches:
    - require.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - tifffile >2020.10.1
    - numpy
    - imagecodecs

test:
  imports:
    - pyometiff
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/filippocastelli/pyometiff
  summary: Read and Write OME-TIFFs in Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
